### ISSUE TITLE
'utf-8' codec can't decode byte 0x8b

### ISSUE THREAD

**Issue by dridk** [0xTCG/aldy#12]
When I run the following command : 

`python -m aldy genotype -p 1813PG.bam -g CYP2D6 1856PG.bam`

I get the following error 

```
'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mydata/miniconda/envs/gatk/lib/python3.6/site-packages/aldy/__main__.py", line 116, in main
    _genotype(gene, output, args)
  File "/mydata/miniconda/envs/gatk/lib/python3.6/site-packages/aldy/__main__.py", line 434, in _genotype
    run(None)
  File "/mydata/miniconda/envs/gatk/lib/python3.6/site-packages/aldy/__main__.py", line 393, in run
    debug=debug,
  File "/mydata/miniconda/envs/gatk/lib/python3.6/site-packages/aldy/genotype.py", line 125, in genotype
    debug=debug,
  File "/mydata/miniconda/envs/gatk/lib/python3.6/site-packages/aldy/sam.py", line 98, in __init__
    self.detect_cn(gene, profile, cn_region)
  File "/mydata/miniconda/envs/gatk/lib/python3.6/site-packages/aldy/sam.py", line 512, in detect_cn
    prof = self._load_profile(profile)
  File "/mydata/miniconda/envs/gatk/lib/python3.6/site-packages/aldy/sam.py", line 571, in _load_profile
    for line in f:
  File "/mydata/miniconda/envs/gatk/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
```

I am investigating...

**Comment by dridk** [comment]
I think I resolved this... It doesn't support "chr" prefix

**Comment by dridk** [comment]
I tried with your reference bam ! Still not working ...  
```

python -m aldy genotype -s cbc -p HG00463.bam  -g CYP2D6 HG00463.bam  --debug debuginfo
*** Aldy v2.2.3 (Python 3.6.10, linux) ***
*** (c) 2016-2020 Aldy Authors & Indiana University Bloomington. All rights reserved.
*** Free for non-commercial/academic use only.
Genotyping sample HG00463.bam...
Preparing debug archive...
'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/mydata/miniconda/envs/gatk/lib/python3.6/site-packages/aldy/__main__.py", line 116, in main
    _genotype(gene, output, args)
  File "/mydata/miniconda/envs/gatk/lib/python3.6/site-packages/aldy/__main__.py", line 426, in _genotype
    run(prefix)
  File "/mydata/miniconda/envs/gatk/lib/python3.6/site-packages/aldy/__main__.py", line 393, in run
    debug=debug,
  File "/mydata/miniconda/envs/gatk/lib/python3.6/site-packages/aldy/genotype.py", line 125, in genotype
    debug=debug,
  File "/mydata/miniconda/envs/gatk/lib/python3.6/site-packages/aldy/sam.py", line 98, in __init__
    self.detect_cn(gene, profile, cn_region)
  File "/mydata/miniconda/envs/gatk/lib/python3.6/site-packages/aldy/sam.py", line 512, in detect_cn
    prof = self._load_profile(profile)
  File "/mydata/miniconda/envs/gatk/lib/python3.6/site-packages/aldy/sam.py", line 571, in _load_profile
    for line in f:
  File "/mydata/miniconda/envs/gatk/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
```

**Comment by inumanag** [comment]
Can you use `-p illumina` if you are using Illumina-sequenced WGS sample?

**Comment by inumanag** [comment]
Found it... can you please try the latest commit?

**Comment by inumanag** [comment]
Closing due to the inactivity.
