### ISSUE TITLE
RecursionError: maximum recursion depth exceeded in comparison

### ISSUE THREAD

**Issue by NTNguyen13** [0xTCG/aldy#14]
Hi, I'm trying Aldy for genotyping PGX genes, for some run, I encounter this error:
maximum recursion depth exceeded in comparison
```
Traceback (most recent call last):
  File "/home/nguyen/anaconda3/envs/aldy/lib/python3.6/site-packages/aldy/__main__.py", line 117, in main
    _genotype(gene, output, args)
  File "/home/nguyen/anaconda3/envs/aldy/lib/python3.6/site-packages/aldy/__main__.py", line 433, in _genotype
    run(None)
  File "/home/nguyen/anaconda3/envs/aldy/lib/python3.6/site-packages/aldy/__main__.py", line 392, in run
    debug=debug,
  File "/home/nguyen/anaconda3/envs/aldy/lib/python3.6/site-packages/aldy/genotype.py", line 185, in genotype
    debug=debug,
  File "/home/nguyen/anaconda3/envs/aldy/lib/python3.6/site-packages/aldy/major.py", line 75, in estimate_major
    gene, alleles, coverage, cn_solution, solver, gap, identifier, debug
  File "/home/nguyen/anaconda3/envs/aldy/lib/python3.6/site-packages/aldy/major.py", line 259, in solve_major_model
    for status, opt, sol in model.solutions(gap):
  File "/home/nguyen/anaconda3/envs/aldy/lib/python3.6/site-packages/aldy/lpinterface.py", line 268, in solutions
    yield from self.solutions(gap, best_obj, limit, iteration + 1, init)
  File "/home/nguyen/anaconda3/envs/aldy/lib/python3.6/site-packages/aldy/lpinterface.py", line 268, in solutions
    yield from self.solutions(gap, best_obj, limit, iteration + 1, init)
  File "/home/nguyen/anaconda3/envs/aldy/lib/python3.6/site-packages/aldy/lpinterface.py", line 268, in solutions
    yield from self.solutions(gap, best_obj, limit, iteration + 1, init)
  [Previous line repeated 972 more times]
  File "/home/nguyen/anaconda3/envs/aldy/lib/python3.6/site-packages/aldy/lpinterface.py", line 267, in solutions
    self.addConstr(self.quicksum(vv.values()) <= len(vv) - 1)
  File "/home/nguyen/anaconda3/envs/aldy/lib/python3.6/site-packages/aldy/lpinterface.py", line 397, in quicksum
    return self.model.Sum(expr)
  File "/home/nguyen/anaconda3/envs/aldy/lib/python3.6/site-packages/ortools/linear_solver/pywraplp.py", line 468, in Sum
    result = SumArray(expr_array)
  File "/home/nguyen/anaconda3/envs/aldy/lib/python3.6/site-packages/ortools/linear_solver/linear_solver_natural_api.py", line 209, in __init__
    self.__array = [CastToLinExp(elem) for elem in array]
  File "/home/nguyen/anaconda3/envs/aldy/lib/python3.6/site-packages/ortools/linear_solver/linear_solver_natural_api.py", line 209, in <listcomp>
    self.__array = [CastToLinExp(elem) for elem in array]
  File "/home/nguyen/anaconda3/envs/aldy/lib/python3.6/site-packages/ortools/linear_solver/linear_solver_natural_api.py", line 53, in CastToLinExp
    if isinstance(v, numbers.Number):
  File "/home/nguyen/anaconda3/envs/aldy/lib/python3.6/abc.py", line 190, in __instancecheck__
    subclass in cls._abc_negative_cache):
  File "/home/nguyen/anaconda3/envs/aldy/lib/python3.6/_weakrefset.py", line 75, in __contains__
    return wr in self.data
RecursionError: maximum recursion depth exceeded in comparison

```

I found that the error comes from reaching maximum recursive depth and can be raised by using `sys.setrecursionlimit(1500)`, but I also heard that it's not safe for doing so. Can this be improved? 

I also wonder about genotyping multiple genes at once, is this possible to do it?

**Comment by inumanag** [comment]
Hi @NTNguyen13,

What is your current recursion limit (you can get it by running `python -c 'import sys; print(sys.getrecursionlimit())')? It seems that it is really low--- the default is usually 1000.

**Comment by NTNguyen13** [comment]
> Hi @NTNguyen13,
> 
> What is your current recursion limit (you can get it by running
> `python -c 'import sys; print(sys.getrecursionlimit())'`? It seems that it is really low--- the default is usually 1000.

Hi, my default is 1000

**Comment by inumanag** [comment]
Hm, that is weird then... seems that the problem is in `ortools` package. Would you mind sharing the dataset? If not, increasing the recursion limit to 1500 is not dangerous (150000--- maybe, but 1500, not).

For multiple genes: yeah, you can do `-g all`, but it will do all genes. Will add the option later to select 2 or more custom genes.

**Comment by inumanag** [comment]
Closing due to inactivity.
