### ISSUE TITLE
ERROR: gene= cyp2d6, file= S000029_S4842Nr1.bam KeyError('hg38')

### ISSUE THREAD

**Issue by erichards52** [0xTCG/aldy#47]
Hi there,

I've generated my own profile using:
aldy profile S000029_S4842Nr1.bam > panel.profile

But when I attempt to run this with:
aldy genotype -p panel.profile -g cyp2d6 S000029_S4842Nr1.bam

It returns:
🐿  Aldy v4.4 (Python 3.10.6 on Linux 5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.35)
   (c) 2016-2023 Aldy Authors. All rights reserved.
   Free for non-commercial/academic use only.
Genotyping sample S000029_S4842Nr1.bam...
ERROR: gene= cyp2d6, file= S000029_S4842Nr1.bam
KeyError('hg38')
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/aldy/__main__.py", line 122, in main
    _genotype(args.gene, output, args)
  File "/usr/local/lib/python3.10/dist-packages/aldy/__main__.py", line 443, in _genotype
    run(None)
  File "/usr/local/lib/python3.10/dist-packages/aldy/__main__.py", line 393, in run
    _ = genotype(
  File "/usr/local/lib/python3.10/dist-packages/aldy/genotype.py", line 183, in genotype
    profile = Profile.load(gene, profile_name, cn_region, **params)
  File "/usr/local/lib/python3.10/dist-packages/aldy/profile.py", line 262, in load
    GRange(*prof["neutral"][gene.genome]),
KeyError: 'hg38'

Just wondering if this is an error on my side and if it can be rectified?

Thank you.

**Comment by inumanag** [comment]
Oh, can you please try adding `--genome hg38` here?

**Comment by erichards52** [comment]
Thanks for getting back to me!

I've just attempted this: 
aldy genotype -p panel.profile --genome hg38 -g cyp2d6 S000029_S4842Nr1.bam

But it's still returning:
🐿  Aldy v4.4 (Python 3.10.6 on Linux 5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.35)
   (c) 2016-2023 Aldy Authors. All rights reserved.
   Free for non-commercial/academic use only.
Genotyping sample S000029_S4842Nr1.bam...
ERROR: gene= CYP2D6, file= S000029_S4842Nr1.bam
KeyError('hg38')
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/aldy/__main__.py", line 122, in main
    _genotype(args.gene, output, args)
  File "/usr/local/lib/python3.10/dist-packages/aldy/__main__.py", line 443, in _genotype
    run(None)
  File "/usr/local/lib/python3.10/dist-packages/aldy/__main__.py", line 393, in run
    _ = genotype(
  File "/usr/local/lib/python3.10/dist-packages/aldy/genotype.py", line 183, in genotype
    profile = Profile.load(gene, profile_name, cn_region, **params)
  File "/usr/local/lib/python3.10/dist-packages/aldy/profile.py", line 262, in load
    GRange(*prof["neutral"][gene.genome]),
KeyError: 'hg38'

**Comment by inumanag** [comment]
A question: did you use the same Aldy version to generate the profile? You need to generate profile with the same version and with  `--genome hg38`.

**Comment by pbrennan-mvz** [comment]
Is there any update on this? I am having this same issue. I tried adding "--genome hg38", but the problem still remains.

```
aldy genotype -p my-cool-tech.profile -g cyp2d6  --genome hg38 21103663_Pharmaco.bam
🐿  Aldy v4.4 (Python 3.7.5 on Linux 3.10.0-1160.83.1.el7.x86_64-x86_64-with-centos-7.9.2009-Core)
   (c) 2016-2023 Aldy Authors. All rights reserved.
   Free for non-commercial/academic use only.
Genotyping sample 21103663_Pharmaco.bam...
ERROR: gene= cyp2d6, file= 21103663_Pharmaco.bam
KeyError('hg38')
Traceback (most recent call last):
  File "/home/pbrennan/miniconda3/envs/aldy/lib/python3.7/site-packages/aldy/__main__.py", line 122, in main
    _genotype(args.gene, output, args)
  File "/home/pbrennan/miniconda3/envs/aldy/lib/python3.7/site-packages/aldy/__main__.py", line 443, in _genotype
    run(None)
  File "/home/pbrennan/miniconda3/envs/aldy/lib/python3.7/site-packages/aldy/__main__.py", line 403, in run
    **{k: v for k, v in params.items() if v is not None},
  File "/home/pbrennan/miniconda3/envs/aldy/lib/python3.7/site-packages/aldy/genotype.py", line 183, in genotype
    profile = Profile.load(gene, profile_name, cn_region, **params)
  File "/home/pbrennan/miniconda3/envs/aldy/lib/python3.7/site-packages/aldy/profile.py", line 262, in load
    GRange(*prof["neutral"][gene.genome]),
KeyError: 'hg38'
```

**Comment by inumanag** [comment]
You need `--genome hg38` also when generating `my-cool-tech.profile` with `aldy profile`. The fix (which is a nicer error message) will be released in the next version (no ETA at this moment).
