### ISSUE TITLE
Issues calling long read whole genome sequencing

### ISSUE THREAD

**Issue by anh151** [0xTCG/aldy#63]
Hello,
I am trying to run Aldy to call CYP2D6 on a set of samples that were genotyped using PacBio long-read whole genome sequencing using 8x coverage. The current profiles available for Aldy use targeted long-read sequencing which does not work for these samples as coverage is low. I tried creating my own profile using one of the samples, but I get the error below:
```
/home/jupyter/workspaces/piii03variantfrequencyprojectpgxcontrolled/bin/python/bin/python3.9 -m aldy profile --param sam_long_reads=true --genome hg38 123456.bam > long_read.profile
```

```bash
🐿  Aldy v4.4 (Python 3.9.15 on Linux 5.10.0-0.deb10.16-amd64-x86_64-with-glibc2.31)
   (c) 2016-2023 Aldy Authors. All rights reserved.
   Free for non-commercial/academic use only.
Ignoring utr3 in 5.001
Ignoring utr3 in 7.001
Ignoring utr3 in 8.001
Ignoring utr3 in 10.001
Ignoring utr3 in 19.001
Ignoring utr3 in 24.001
Ignoring utr3 in 24.002
Ignoring utr3 in 28.001
Ignoring utr3 in 28.002
Ignoring utr3 in 35.001
Ignoring utr3 in 35.002
Ignoring utr3 in 36.001
Ignoring utr3 in 37.001
Scanning chr1:59890307-109696745...
Scanning chr2:233583743-233776299...
Scanning chr4:69050374-69114287...
Scanning chr6:18125310-18161143...
Scanning chr7:977198-117718971...
/bin/bash: line 1: 16913 Killed                  /home/jupyter/workspaces/piii03variantfrequencyprojectpgxcontrolled/bin/python/bin/python3.9 -m aldy profile --param sam_long_reads=true --genome hg38 123456.bam > long_read.profile
```

Thanks,
Andrew

**Comment by inumanag** [comment]
Hi @anh151 

What environment are you using? This looks like your environment is memory constrained; running `/usr/bin/time -v aldy ...` will give you some idea how much memory Aldy used before getting killed. This step in general should not use much memory, but maybe ultra-long reads adversely impact its memory usage. 

Are these samples public btw—if so I can take a look as well?

**Comment by anh151** [comment]
Hi @inumanag 
Thanks for the advice. It was a memory issue. Peak memory usage was ~20GB. These samples are from All of Us.

I do now get an error that appears to be a bug as shown below.

```python
🐿  Aldy v4.4 (Python 3.9.15 on Linux 5.15.133+-x86_64-with-glibc2.31)
   (c) 2016-2023 Aldy Authors. All rights reserved.
   Free for non-commercial/academic use only.
Ignoring utr3 in 5.001
Ignoring utr3 in 7.001
Ignoring utr3 in 8.001
Ignoring utr3 in 10.001
Ignoring utr3 in 19.001
Ignoring utr3 in 24.001
Ignoring utr3 in 24.002
Ignoring utr3 in 28.001
Ignoring utr3 in 28.002
Ignoring utr3 in 35.001
Ignoring utr3 in 35.002
Ignoring utr3 in 36.001
Ignoring utr3 in 37.001
Scanning chr1:59890307-109696745...
Scanning chr2:233583743-233776299...
Scanning chr4:69050374-69114287...
Scanning chr6:18125310-18161143...
Scanning chr7:977198-117718971...
Scanning chr8:18164461-18404213...
Scanning chr10:94756680-133542116...
Scanning chr11:14875008-67589653...
Scanning chr12:21125193-21242796...
Scanning chr13:48031566-48055742...
Scanning chr15:74716541-74759607...
Scanning chr16:31087853-31100955...
Scanning chr19:15875023-41210539...
Scanning chr22:19935739-42153258...
Scanning chrX:154528390-154553572...
ERROR: file= bams/123456.bam
AttributeError("'Profile' object has no attribute '_parse_params'")
Traceback (most recent call last):
  File "/home/jupyter/.local/lib/python3.9/site-packages/aldy/__main__.py", line 106, in main
    p = Profile.get_sam_profile_data(
  File "/home/jupyter/.local/lib/python3.9/site-packages/aldy/profile.py", line 378, in get_sam_profile_data
    for k, v in Profile("")._parse_params(params).items():
AttributeError: 'Profile' object has no attribute '_parse_params'
```
